// Generated by gencpp from file yehuh_mouse/LightSensorValues.msg
// DO NOT EDIT!


#ifndef YEHUH_MOUSE_MESSAGE_LIGHTSENSORVALUES_H
#define YEHUH_MOUSE_MESSAGE_LIGHTSENSORVALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yehuh_mouse
{
template <class ContainerAllocator>
struct LightSensorValues_
{
  typedef LightSensorValues_<ContainerAllocator> Type;

  LightSensorValues_()
    : right_forward(0)
    , right_side(0)
    , left_side(0)
    , left_forward(0)  {
    }
  LightSensorValues_(const ContainerAllocator& _alloc)
    : right_forward(0)
    , right_side(0)
    , left_side(0)
    , left_forward(0)  {
  (void)_alloc;
    }



   typedef int16_t _right_forward_type;
  _right_forward_type right_forward;

   typedef int16_t _right_side_type;
  _right_side_type right_side;

   typedef int16_t _left_side_type;
  _left_side_type left_side;

   typedef int16_t _left_forward_type;
  _left_forward_type left_forward;





  typedef boost::shared_ptr< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> const> ConstPtr;

}; // struct LightSensorValues_

typedef ::yehuh_mouse::LightSensorValues_<std::allocator<void> > LightSensorValues;

typedef boost::shared_ptr< ::yehuh_mouse::LightSensorValues > LightSensorValuesPtr;
typedef boost::shared_ptr< ::yehuh_mouse::LightSensorValues const> LightSensorValuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yehuh_mouse::LightSensorValues_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yehuh_mouse::LightSensorValues_<ContainerAllocator1> & lhs, const ::yehuh_mouse::LightSensorValues_<ContainerAllocator2> & rhs)
{
  return lhs.right_forward == rhs.right_forward &&
    lhs.right_side == rhs.right_side &&
    lhs.left_side == rhs.left_side &&
    lhs.left_forward == rhs.left_forward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yehuh_mouse::LightSensorValues_<ContainerAllocator1> & lhs, const ::yehuh_mouse::LightSensorValues_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yehuh_mouse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa26acaa6485ef64ceca927a62524c60";
  }

  static const char* value(const ::yehuh_mouse::LightSensorValues_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa26acaa6485ef64ULL;
  static const uint64_t static_value2 = 0xceca927a62524c60ULL;
};

template<class ContainerAllocator>
struct DataType< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yehuh_mouse/LightSensorValues";
  }

  static const char* value(const ::yehuh_mouse::LightSensorValues_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 right_forward\n"
"int16 right_side\n"
"int16 left_side \n"
"int16 left_forward\n"
;
  }

  static const char* value(const ::yehuh_mouse::LightSensorValues_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right_forward);
      stream.next(m.right_side);
      stream.next(m.left_side);
      stream.next(m.left_forward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightSensorValues_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yehuh_mouse::LightSensorValues_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yehuh_mouse::LightSensorValues_<ContainerAllocator>& v)
  {
    s << indent << "right_forward: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_forward);
    s << indent << "right_side: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_side);
    s << indent << "left_side: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_side);
    s << indent << "left_forward: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_forward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YEHUH_MOUSE_MESSAGE_LIGHTSENSORVALUES_H
