// Generated by gencpp from file yehuh_mouse/TimedMotionResponse.msg
// DO NOT EDIT!


#ifndef YEHUH_MOUSE_MESSAGE_TIMEDMOTIONRESPONSE_H
#define YEHUH_MOUSE_MESSAGE_TIMEDMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yehuh_mouse
{
template <class ContainerAllocator>
struct TimedMotionResponse_
{
  typedef TimedMotionResponse_<ContainerAllocator> Type;

  TimedMotionResponse_()
    : sucess(false)  {
    }
  TimedMotionResponse_(const ContainerAllocator& _alloc)
    : sucess(false)  {
  (void)_alloc;
    }



   typedef uint8_t _sucess_type;
  _sucess_type sucess;





  typedef boost::shared_ptr< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TimedMotionResponse_

typedef ::yehuh_mouse::TimedMotionResponse_<std::allocator<void> > TimedMotionResponse;

typedef boost::shared_ptr< ::yehuh_mouse::TimedMotionResponse > TimedMotionResponsePtr;
typedef boost::shared_ptr< ::yehuh_mouse::TimedMotionResponse const> TimedMotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator1> & lhs, const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sucess == rhs.sucess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator1> & lhs, const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yehuh_mouse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e8ad2f62d0edf01ac96b1e92459b490";
  }

  static const char* value(const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e8ad2f62d0edf01ULL;
  static const uint64_t static_value2 = 0xac96b1e92459b490ULL;
};

template<class ContainerAllocator>
struct DataType< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yehuh_mouse/TimedMotionResponse";
  }

  static const char* value(const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool sucess\n"
"\n"
;
  }

  static const char* value(const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sucess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimedMotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yehuh_mouse::TimedMotionResponse_<ContainerAllocator>& v)
  {
    s << indent << "sucess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sucess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YEHUH_MOUSE_MESSAGE_TIMEDMOTIONRESPONSE_H
