// Generated by gencpp from file yehuh_mouse/TimedMotion.msg
// DO NOT EDIT!


#ifndef YEHUH_MOUSE_MESSAGE_TIMEDMOTION_H
#define YEHUH_MOUSE_MESSAGE_TIMEDMOTION_H

#include <ros/service_traits.h>


#include <yehuh_mouse/TimedMotionRequest.h>
#include <yehuh_mouse/TimedMotionResponse.h>


namespace yehuh_mouse
{

struct TimedMotion
{

typedef TimedMotionRequest Request;
typedef TimedMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TimedMotion
} // namespace yehuh_mouse


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yehuh_mouse::TimedMotion > {
  static const char* value()
  {
    return "a2afe94fc48ef0c10e4ed921900e9e4a";
  }

  static const char* value(const ::yehuh_mouse::TimedMotion&) { return value(); }
};

template<>
struct DataType< ::yehuh_mouse::TimedMotion > {
  static const char* value()
  {
    return "yehuh_mouse/TimedMotion";
  }

  static const char* value(const ::yehuh_mouse::TimedMotion&) { return value(); }
};


// service_traits::MD5Sum< ::yehuh_mouse::TimedMotionRequest> should match
// service_traits::MD5Sum< ::yehuh_mouse::TimedMotion >
template<>
struct MD5Sum< ::yehuh_mouse::TimedMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yehuh_mouse::TimedMotion >::value();
  }
  static const char* value(const ::yehuh_mouse::TimedMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yehuh_mouse::TimedMotionRequest> should match
// service_traits::DataType< ::yehuh_mouse::TimedMotion >
template<>
struct DataType< ::yehuh_mouse::TimedMotionRequest>
{
  static const char* value()
  {
    return DataType< ::yehuh_mouse::TimedMotion >::value();
  }
  static const char* value(const ::yehuh_mouse::TimedMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yehuh_mouse::TimedMotionResponse> should match
// service_traits::MD5Sum< ::yehuh_mouse::TimedMotion >
template<>
struct MD5Sum< ::yehuh_mouse::TimedMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yehuh_mouse::TimedMotion >::value();
  }
  static const char* value(const ::yehuh_mouse::TimedMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yehuh_mouse::TimedMotionResponse> should match
// service_traits::DataType< ::yehuh_mouse::TimedMotion >
template<>
struct DataType< ::yehuh_mouse::TimedMotionResponse>
{
  static const char* value()
  {
    return DataType< ::yehuh_mouse::TimedMotion >::value();
  }
  static const char* value(const ::yehuh_mouse::TimedMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YEHUH_MOUSE_MESSAGE_TIMEDMOTION_H
