// Auto-generated. Do not edit!

// (in-package raspimouse_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MusicFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.remaining_steps = null;
    }
    else {
      if (initObj.hasOwnProperty('remaining_steps')) {
        this.remaining_steps = initObj.remaining_steps
      }
      else {
        this.remaining_steps = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MusicFeedback
    // Serialize message field [remaining_steps]
    bufferOffset = _serializer.uint32(obj.remaining_steps, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MusicFeedback
    let len;
    let data = new MusicFeedback(null);
    // Deserialize message field [remaining_steps]
    data.remaining_steps = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'raspimouse_ros/MusicFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd5eff3ade2f012fc853f922d89a1a6cf';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint32 remaining_steps
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MusicFeedback(null);
    if (msg.remaining_steps !== undefined) {
      resolved.remaining_steps = msg.remaining_steps;
    }
    else {
      resolved.remaining_steps = 0
    }

    return resolved;
    }
};

module.exports = MusicFeedback;
