// Generated by gencpp from file raspimouse_ros/MotorFreqs.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_MOTORFREQS_H
#define RASPIMOUSE_ROS_MESSAGE_MOTORFREQS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspimouse_ros
{
template <class ContainerAllocator>
struct MotorFreqs_
{
  typedef MotorFreqs_<ContainerAllocator> Type;

  MotorFreqs_()
    : left(0)
    , right(0)  {
    }
  MotorFreqs_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_type;
  _left_type left;

   typedef int16_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> const> ConstPtr;

}; // struct MotorFreqs_

typedef ::raspimouse_ros::MotorFreqs_<std::allocator<void> > MotorFreqs;

typedef boost::shared_ptr< ::raspimouse_ros::MotorFreqs > MotorFreqsPtr;
typedef boost::shared_ptr< ::raspimouse_ros::MotorFreqs const> MotorFreqsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspimouse_ros::MotorFreqs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raspimouse_ros::MotorFreqs_<ContainerAllocator1> & lhs, const ::raspimouse_ros::MotorFreqs_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raspimouse_ros::MotorFreqs_<ContainerAllocator1> & lhs, const ::raspimouse_ros::MotorFreqs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raspimouse_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09d1b2323a1aeae9343e81809a820b60";
  }

  static const char* value(const ::raspimouse_ros::MotorFreqs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09d1b2323a1aeae9ULL;
  static const uint64_t static_value2 = 0x343e81809a820b60ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspimouse_ros/MotorFreqs";
  }

  static const char* value(const ::raspimouse_ros::MotorFreqs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 left\n"
"int16 right\n"
;
  }

  static const char* value(const ::raspimouse_ros::MotorFreqs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorFreqs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspimouse_ros::MotorFreqs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspimouse_ros::MotorFreqs_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_MOTORFREQS_H
