// Generated by gencpp from file raspimouse_ros/MusicResult.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_MUSICRESULT_H
#define RASPIMOUSE_ROS_MESSAGE_MUSICRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspimouse_ros
{
template <class ContainerAllocator>
struct MusicResult_
{
  typedef MusicResult_<ContainerAllocator> Type;

  MusicResult_()
    : finished(false)  {
    }
  MusicResult_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::raspimouse_ros::MusicResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspimouse_ros::MusicResult_<ContainerAllocator> const> ConstPtr;

}; // struct MusicResult_

typedef ::raspimouse_ros::MusicResult_<std::allocator<void> > MusicResult;

typedef boost::shared_ptr< ::raspimouse_ros::MusicResult > MusicResultPtr;
typedef boost::shared_ptr< ::raspimouse_ros::MusicResult const> MusicResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspimouse_ros::MusicResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspimouse_ros::MusicResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raspimouse_ros::MusicResult_<ContainerAllocator1> & lhs, const ::raspimouse_ros::MusicResult_<ContainerAllocator2> & rhs)
{
  return lhs.finished == rhs.finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raspimouse_ros::MusicResult_<ContainerAllocator1> & lhs, const ::raspimouse_ros::MusicResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raspimouse_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::MusicResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::MusicResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::MusicResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::raspimouse_ros::MusicResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspimouse_ros/MusicResult";
  }

  static const char* value(const ::raspimouse_ros::MusicResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool finished\n"
;
  }

  static const char* value(const ::raspimouse_ros::MusicResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MusicResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspimouse_ros::MusicResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspimouse_ros::MusicResult_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_MUSICRESULT_H
