// Generated by gencpp from file raspimouse_ros/PutMotorFreqs.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_PUTMOTORFREQS_H
#define RASPIMOUSE_ROS_MESSAGE_PUTMOTORFREQS_H

#include <ros/service_traits.h>


#include <raspimouse_ros/PutMotorFreqsRequest.h>
#include <raspimouse_ros/PutMotorFreqsResponse.h>


namespace raspimouse_ros
{

struct PutMotorFreqs
{

typedef PutMotorFreqsRequest Request;
typedef PutMotorFreqsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PutMotorFreqs
} // namespace raspimouse_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::raspimouse_ros::PutMotorFreqs > {
  static const char* value()
  {
    return "6bc107b4d0c4eadcc189122b167e76e6";
  }

  static const char* value(const ::raspimouse_ros::PutMotorFreqs&) { return value(); }
};

template<>
struct DataType< ::raspimouse_ros::PutMotorFreqs > {
  static const char* value()
  {
    return "raspimouse_ros/PutMotorFreqs";
  }

  static const char* value(const ::raspimouse_ros::PutMotorFreqs&) { return value(); }
};


// service_traits::MD5Sum< ::raspimouse_ros::PutMotorFreqsRequest> should match
// service_traits::MD5Sum< ::raspimouse_ros::PutMotorFreqs >
template<>
struct MD5Sum< ::raspimouse_ros::PutMotorFreqsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::raspimouse_ros::PutMotorFreqs >::value();
  }
  static const char* value(const ::raspimouse_ros::PutMotorFreqsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::raspimouse_ros::PutMotorFreqsRequest> should match
// service_traits::DataType< ::raspimouse_ros::PutMotorFreqs >
template<>
struct DataType< ::raspimouse_ros::PutMotorFreqsRequest>
{
  static const char* value()
  {
    return DataType< ::raspimouse_ros::PutMotorFreqs >::value();
  }
  static const char* value(const ::raspimouse_ros::PutMotorFreqsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::raspimouse_ros::PutMotorFreqsResponse> should match
// service_traits::MD5Sum< ::raspimouse_ros::PutMotorFreqs >
template<>
struct MD5Sum< ::raspimouse_ros::PutMotorFreqsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::raspimouse_ros::PutMotorFreqs >::value();
  }
  static const char* value(const ::raspimouse_ros::PutMotorFreqsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::raspimouse_ros::PutMotorFreqsResponse> should match
// service_traits::DataType< ::raspimouse_ros::PutMotorFreqs >
template<>
struct DataType< ::raspimouse_ros::PutMotorFreqsResponse>
{
  static const char* value()
  {
    return DataType< ::raspimouse_ros::PutMotorFreqs >::value();
  }
  static const char* value(const ::raspimouse_ros::PutMotorFreqsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_PUTMOTORFREQS_H
