// Generated by gencpp from file raspimouse_ros/PutMotorFreqsRequest.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_PUTMOTORFREQSREQUEST_H
#define RASPIMOUSE_ROS_MESSAGE_PUTMOTORFREQSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspimouse_ros
{
template <class ContainerAllocator>
struct PutMotorFreqsRequest_
{
  typedef PutMotorFreqsRequest_<ContainerAllocator> Type;

  PutMotorFreqsRequest_()
    : left(0)
    , right(0)
    , duration(0)  {
    }
  PutMotorFreqsRequest_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)
    , duration(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_type;
  _left_type left;

   typedef int16_t _right_type;
  _right_type right;

   typedef int32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PutMotorFreqsRequest_

typedef ::raspimouse_ros::PutMotorFreqsRequest_<std::allocator<void> > PutMotorFreqsRequest;

typedef boost::shared_ptr< ::raspimouse_ros::PutMotorFreqsRequest > PutMotorFreqsRequestPtr;
typedef boost::shared_ptr< ::raspimouse_ros::PutMotorFreqsRequest const> PutMotorFreqsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator1> & lhs, const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator1> & lhs, const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raspimouse_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c844e9c321acd0da2750307eb75f9e34";
  }

  static const char* value(const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc844e9c321acd0daULL;
  static const uint64_t static_value2 = 0x2750307eb75f9e34ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspimouse_ros/PutMotorFreqsRequest";
  }

  static const char* value(const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 left\n"
"int16 right\n"
"int32 duration\n"
;
  }

  static const char* value(const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PutMotorFreqsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspimouse_ros::PutMotorFreqsRequest_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
    s << indent << "duration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_PUTMOTORFREQSREQUEST_H
