// Generated by gencpp from file raspimouse_ros/SwitchMotorsResponse.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSRESPONSE_H
#define RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspimouse_ros
{
template <class ContainerAllocator>
struct SwitchMotorsResponse_
{
  typedef SwitchMotorsResponse_<ContainerAllocator> Type;

  SwitchMotorsResponse_()
    : accepted(false)  {
    }
  SwitchMotorsResponse_(const ContainerAllocator& _alloc)
    : accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _accepted_type;
  _accepted_type accepted;





  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchMotorsResponse_

typedef ::raspimouse_ros::SwitchMotorsResponse_<std::allocator<void> > SwitchMotorsResponse;

typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse > SwitchMotorsResponsePtr;
typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsResponse const> SwitchMotorsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator1> & lhs, const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.accepted == rhs.accepted;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator1> & lhs, const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raspimouse_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ea39b897cc8620c46aaa14cb60920cd";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ea39b897cc8620cULL;
  static const uint64_t static_value2 = 0x46aaa14cb60920cdULL;
};

template<class ContainerAllocator>
struct DataType< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspimouse_ros/SwitchMotorsResponse";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool accepted\n"
"\n"
;
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchMotorsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspimouse_ros::SwitchMotorsResponse_<ContainerAllocator>& v)
  {
    s << indent << "accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSRESPONSE_H
