// Generated by gencpp from file raspimouse_ros/SwitchMotorsRequest.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSREQUEST_H
#define RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspimouse_ros
{
template <class ContainerAllocator>
struct SwitchMotorsRequest_
{
  typedef SwitchMotorsRequest_<ContainerAllocator> Type;

  SwitchMotorsRequest_()
    : on(false)  {
    }
  SwitchMotorsRequest_(const ContainerAllocator& _alloc)
    : on(false)  {
  (void)_alloc;
    }



   typedef uint8_t _on_type;
  _on_type on;





  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchMotorsRequest_

typedef ::raspimouse_ros::SwitchMotorsRequest_<std::allocator<void> > SwitchMotorsRequest;

typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest > SwitchMotorsRequestPtr;
typedef boost::shared_ptr< ::raspimouse_ros::SwitchMotorsRequest const> SwitchMotorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator1> & lhs, const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.on == rhs.on;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator1> & lhs, const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raspimouse_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74983d2ffe4877de8ae30b7a94625c41";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74983d2ffe4877deULL;
  static const uint64_t static_value2 = 0x8ae30b7a94625c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspimouse_ros/SwitchMotorsRequest";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool on\n"
;
  }

  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchMotorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspimouse_ros::SwitchMotorsRequest_<ContainerAllocator>& v)
  {
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORSREQUEST_H
