// Generated by gencpp from file raspimouse_ros/SwitchMotors.msg
// DO NOT EDIT!


#ifndef RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORS_H
#define RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORS_H

#include <ros/service_traits.h>


#include <raspimouse_ros/SwitchMotorsRequest.h>
#include <raspimouse_ros/SwitchMotorsResponse.h>


namespace raspimouse_ros
{

struct SwitchMotors
{

typedef SwitchMotorsRequest Request;
typedef SwitchMotorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchMotors
} // namespace raspimouse_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::raspimouse_ros::SwitchMotors > {
  static const char* value()
  {
    return "8047b8b6170ed41bf326931d2c1e2525";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotors&) { return value(); }
};

template<>
struct DataType< ::raspimouse_ros::SwitchMotors > {
  static const char* value()
  {
    return "raspimouse_ros/SwitchMotors";
  }

  static const char* value(const ::raspimouse_ros::SwitchMotors&) { return value(); }
};


// service_traits::MD5Sum< ::raspimouse_ros::SwitchMotorsRequest> should match
// service_traits::MD5Sum< ::raspimouse_ros::SwitchMotors >
template<>
struct MD5Sum< ::raspimouse_ros::SwitchMotorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::raspimouse_ros::SwitchMotors >::value();
  }
  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::raspimouse_ros::SwitchMotorsRequest> should match
// service_traits::DataType< ::raspimouse_ros::SwitchMotors >
template<>
struct DataType< ::raspimouse_ros::SwitchMotorsRequest>
{
  static const char* value()
  {
    return DataType< ::raspimouse_ros::SwitchMotors >::value();
  }
  static const char* value(const ::raspimouse_ros::SwitchMotorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::raspimouse_ros::SwitchMotorsResponse> should match
// service_traits::MD5Sum< ::raspimouse_ros::SwitchMotors >
template<>
struct MD5Sum< ::raspimouse_ros::SwitchMotorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::raspimouse_ros::SwitchMotors >::value();
  }
  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::raspimouse_ros::SwitchMotorsResponse> should match
// service_traits::DataType< ::raspimouse_ros::SwitchMotors >
template<>
struct DataType< ::raspimouse_ros::SwitchMotorsResponse>
{
  static const char* value()
  {
    return DataType< ::raspimouse_ros::SwitchMotors >::value();
  }
  static const char* value(const ::raspimouse_ros::SwitchMotorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RASPIMOUSE_ROS_MESSAGE_SWITCHMOTORS_H
