(cl:defpackage raspimouse_ros-msg
  (:use )
  (:export
   "<LIGHTSENSORVALUES>"
   "LIGHTSENSORVALUES"
   "<MOTORFREQS>"
   "MOTORFREQS"
   "<MUSICACTION>"
   "MUSICACTION"
   "<MUSICACTIONFEEDBACK>"
   "MUSICACTIONFEEDBACK"
   "<MUSICACTIONGOAL>"
   "MUSICACTIONGOAL"
   "<MUSICACTIONRESULT>"
   "MUSICACTIONRESULT"
   "<MUSICFEEDBACK>"
   "MUSICFEEDBACK"
   "<MUSICGOAL>"
   "MUSICGOAL"
   "<MUSICRESULT>"
   "MUSICRESULT"
   "<SWITCHES>"
   "SWITCHES"
  ))

