; Auto-generated. Do not edit!


(cl:in-package raspimouse_ros-msg)


;//! \htmlinclude MusicFeedback.msg.html

(cl:defclass <MusicFeedback> (roslisp-msg-protocol:ros-message)
  ((remaining_steps
    :reader remaining_steps
    :initarg :remaining_steps
    :type cl:integer
    :initform 0))
)

(cl:defclass MusicFeedback (<MusicFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MusicFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MusicFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name raspimouse_ros-msg:<MusicFeedback> is deprecated: use raspimouse_ros-msg:MusicFeedback instead.")))

(cl:ensure-generic-function 'remaining_steps-val :lambda-list '(m))
(cl:defmethod remaining_steps-val ((m <MusicFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader raspimouse_ros-msg:remaining_steps-val is deprecated.  Use raspimouse_ros-msg:remaining_steps instead.")
  (remaining_steps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MusicFeedback>) ostream)
  "Serializes a message object of type '<MusicFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'remaining_steps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'remaining_steps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'remaining_steps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'remaining_steps)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MusicFeedback>) istream)
  "Deserializes a message object of type '<MusicFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'remaining_steps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'remaining_steps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'remaining_steps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'remaining_steps)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MusicFeedback>)))
  "Returns string type for a message object of type '<MusicFeedback>"
  "raspimouse_ros/MusicFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MusicFeedback)))
  "Returns string type for a message object of type 'MusicFeedback"
  "raspimouse_ros/MusicFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MusicFeedback>)))
  "Returns md5sum for a message object of type '<MusicFeedback>"
  "d5eff3ade2f012fc853f922d89a1a6cf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MusicFeedback)))
  "Returns md5sum for a message object of type 'MusicFeedback"
  "d5eff3ade2f012fc853f922d89a1a6cf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MusicFeedback>)))
  "Returns full string definition for message of type '<MusicFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 remaining_steps~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MusicFeedback)))
  "Returns full string definition for message of type 'MusicFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 remaining_steps~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MusicFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MusicFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MusicFeedback
    (cl:cons ':remaining_steps (remaining_steps msg))
))
