; Auto-generated. Do not edit!


(cl:in-package raspimouse_ros-msg)


;//! \htmlinclude MusicResult.msg.html

(cl:defclass <MusicResult> (roslisp-msg-protocol:ros-message)
  ((finished
    :reader finished
    :initarg :finished
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MusicResult (<MusicResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MusicResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MusicResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name raspimouse_ros-msg:<MusicResult> is deprecated: use raspimouse_ros-msg:MusicResult instead.")))

(cl:ensure-generic-function 'finished-val :lambda-list '(m))
(cl:defmethod finished-val ((m <MusicResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader raspimouse_ros-msg:finished-val is deprecated.  Use raspimouse_ros-msg:finished instead.")
  (finished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MusicResult>) ostream)
  "Serializes a message object of type '<MusicResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finished) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MusicResult>) istream)
  "Deserializes a message object of type '<MusicResult>"
    (cl:setf (cl:slot-value msg 'finished) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MusicResult>)))
  "Returns string type for a message object of type '<MusicResult>"
  "raspimouse_ros/MusicResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MusicResult)))
  "Returns string type for a message object of type 'MusicResult"
  "raspimouse_ros/MusicResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MusicResult>)))
  "Returns md5sum for a message object of type '<MusicResult>"
  "e2797c797e620a950ba704492d72873b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MusicResult)))
  "Returns md5sum for a message object of type 'MusicResult"
  "e2797c797e620a950ba704492d72873b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MusicResult>)))
  "Returns full string definition for message of type '<MusicResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MusicResult)))
  "Returns full string definition for message of type 'MusicResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MusicResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MusicResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MusicResult
    (cl:cons ':finished (finished msg))
))
