(cl:defpackage raspimouse_ros-srv
  (:use )
  (:export
   "PUTMOTORFREQS"
   "<PUTMOTORFREQS-REQUEST>"
   "PUTMOTORFREQS-REQUEST"
   "<PUTMOTORFREQS-RESPONSE>"
   "PUTMOTORFREQS-RESPONSE"
   "SWITCHMOTORS"
   "<SWITCHMOTORS-REQUEST>"
   "SWITCHMOTORS-REQUEST"
   "<SWITCHMOTORS-RESPONSE>"
   "SWITCHMOTORS-RESPONSE"
  ))

